# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Deploy do Módulo

on:
  push:
    branches:
      - main  # Ou a branch em que você deseja acionar o workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'  # Defina a versão do JDK apropriada

      - name: Install Maven
        uses: actions/setup-maven@v3
        with:
          maven-version: '3.8.5'  # Defina a versão do Maven apropriada

      - name: Build NetBeans Module
        run: mvn clean install

      - name: Archive NBM file
        uses: actions/upload-artifact@v3
        with:
          name: netbeans-module
          path: target/*.nbm  # Altere para o caminho onde o arquivo .nbm é gerado
